### ISSUE TITLE
Wish / Idea: invert (transpose) nodes-index table list 

### ISSUE THREAD

**Issue by v01t** [lmenezes/cerebro#12]
Hi,

maybe it will be good visual improvement to invert nodes-index table (nodes as columns, indexes as rows), reason - usually we have more indexes than nodes and scroll-down looks like to be more easy way to find specified index than jump to second/third page as it is currently (besides search by full index name with some part of date)

Additionally index information can be more "thiner" in a matter of row height, so more indexes can be displayed.

**Comment by lmenezes** [comment]
hey @v01t 

someone else has brought up this topic a long time ago in kopf.

I personally don't really have a lot of interest on this idea because for me its more valuable to be able to scroll and see all nodes rather than all indices(this way I can have a complete view of where shards for a given index are located).

I don't dislike the idea, and building it should not be a problem, but I won't be looking into this at the moment. Perhaps when this is a bit more finished/polished, it could be something to consider.
