### ISSUE TITLE
Request: Cluster stats word 

### ISSUE THREAD

**Issue by edperry** [lmenezes/cerebro#134]
Hey one request from us Color blind individuals 

In Kpof, the top bar was "green, yellow, red" and a combinitation of color blindness and laptop angle always made it difficult for me to be sure of the cluster being red yellow or green.

would it be difficult to put the words in this bar as well?

**Comment by lmenezes** [comment]
@edperry of course something can be done about it. I just never considered this, sorry :)

Do you think we can do something better than just placing the word somewhere on the navbar? Perhaps you know of other solutions target at this kind of issues. 

One small improvement I can think of is also adding the colour text on the tab bar together with the favicon that changes colour.

**Comment by edperry** [comment]
There could be all kinds of suggestions, but I would think just a simple would suffice, a giant STOP SIGN would be great :D  but I jest.  I think just adding "red" or something in the colorbar you already have would be more then enough

![image](https://cloud.githubusercontent.com/assets/6684633/26693521/747a0366-46d2-11e7-9719-90eab45b7739.png)

Another suggestion would be to add it right next to the cluster name = hbc_qa (green|yellow|red)  I am not too picky  as I have come to love Kopf and Cerebro  and will default to your preference.

**Comment by lmenezes** [comment]
@edperry sorry it took so long to work on this. at some point it just slipped my mind and I just now found it again.

I ended up adding next to the cluster name(as you mentioned), mostly because i could not figure out any other alternative that looked better. I also added it to the page title, although depending on how long your cluster name is, this won't ever be readable :)
