### ISSUE TITLE
Not show closed indices by default

### ISSUE THREAD

**Issue by darky** [lmenezes/cerebro#160]
By default closed indexes checkbox always plugged on. I plug this off, go to another partition of UI. Go to home again and closed indexes checkbox again pluggen on. I again plug this off.
Why this behaviour? I close indexes, because they are not needed now! But UI force show it me again and again. Very bad UX :-1: 
I try to solve this via https://github.com/lmenezes/cerebro/pull/159, but maybe I was wrong of my code.

**Comment by lmenezes** [comment]
hey @darky 

This is very bad UX for you, for me this works perfectly.

I did close #159 because you just created a fix for an issue that you have, without asking if this was something that I thought was interesting, which I don't(at least in this form). 

Also, the code is not really doing what you think it is, and it doesn't really follow at all the contributing guide https://github.com/lmenezes/cerebro/blob/master/CONTRIBUTING.md

**Comment by darky** [comment]
Ok, compromise, maybe would be good, if UX will save state in Local Storage?

**Comment by lmenezes** [comment]
@darky this could be, but could also be annoying that you keep this across sessions. I anyway don't really have much time atm for working on cerebro, so I won't be looking into this any time soon. If this is such a big deal for you, you can always just build from source and change this on the HTML(its jus ta checkbox, so setting it to false would do the trick).
