### ISSUE TITLE
Cerebro showing "-" as disk usage when it should be showing 0%

### ISSUE THREAD

**Issue by arnabkd** [lmenezes/cerebro#166]
I recently tried to move my data folder and I ended up seeing cerebro report the disk usage as `-`
When I looked at the requests being done in the network tab, I noticed that disk usage was reported as 0% but this was not shown in cerebro. To me, this is confusing and the UI makes it seem as if ES cannot find the data folder at all.

![screen shot 2017-06-20 at 10 53 57 am](https://user-images.githubusercontent.com/1014699/27324888-e78a94b4-55a6-11e7-806c-7a5ce64e59ff.png)

**Comment by gerilya** [comment]
I am experiencing this as well on AWS's d2.2xlarge instances with approx 11TB of disk space while disk stats are shown correctly on i3.2xlarge instances (approx 1.8TB disks).
I think this is caused by .toFloat conversion at https://github.com/lmenezes/cerebro/blob/56d4e6b48c9103c1d9a19ac39f9a9d9982d6aa86/app/models/nodes/Node.scala#L53 which results in percent=0. 
I've confirmed that percent is, indeed, zero in JSON: 
...
      "disk": {
        "total": 12000185286656,
        "available": 11997739245568,
        "percent": 0
      },
...
