### ISSUE TITLE
Password encryption in application.conf?

### ISSUE THREAD

**Issue by mptei** [lmenezes/cerebro#168]
Is it possible to encrypt or scramble the password in the host specification in the application.conf?
I know that security is not much increased by this, but at least it's not so easy to see the passwords.

**Comment by lmenezes** [comment]
@mptei I don't think this actually makes much sense. But, just now I pushed a few changes that allow you to NOT set the credentials on the host(on application.conf), and the app will then prompt you for your credentials. This way no password has to be stored on the file(although, in this case I highly recommend using ssl, since your password will be sent around)
