### ISSUE TITLE
AWS deployment connection issues

### ISSUE THREAD

**Issue by MonnyA** [lmenezes/cerebro#177]
I'm having issues using my browser to access Cerebro deployed on an AWS EC2 server. When I go to http://AWSpublicIP:9000 in my browser (Chrome) I get the default orange Play Framework page saying "Not Found For request 'GET /'"

When setting Logback config to ALL I get the following in stdout when I try to load the page.

`[debug] c.g.i.i.BytecodeGen - Loading class play.api.http.DefaultHttpErrorHandler FastClass with sun.misc.Launcher$AppClassLoader@677327b6`

The rest of the log seems fine.

I'm new to AWS but I'm fairly sure I have the Security Group set up correctly with port TCP 9000. When I remove that inbound rule from the SG my browser gives its generic "cannot connect to host" message.

The rest of the Cerebro config is left as default. Any help would be appreciated.

**Comment by gabriel-tessier** [comment]
Hi,
Hope your problem was solved, but just in case. I installed on AWS EC2 server and don't have any problem, what about your installation?
I set Cerebro to run on localhost port 9000, then I use nginx as proxy on port 9002 so I access
my_public_ip:9002 <--- this port is open in security group only for my IP.
what do you have if in your server terminal you make a curl 127.0.0.1:9000 ?
for me it return this:

` <!DOCTYPE html>
<html lang="en" ng-app="cerebro" ng-init="appVersion = 'v0.6.5'">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge"
....
`
