### ISSUE TITLE
_cat/health in REST (cerebro)

### ISSUE THREAD

**Issue by soume86** [lmenezes/cerebro#182]
I'am trying to run '_cat/health' (GET) via REST (cerebro 6.5) without success. I get the following error message

> {
>   "error": {
>     "root_cause": [
>       {
>         "type": "index_not_found_exception",
>         "reason": "no such index",
>         "resource.type": "index_expression",
>         "resource.id": "",
>         "index_uuid": "_na_",
>         "index": ""
>       }
>     ],
>     "type": "index_not_found_exception",
>     "reason": "no such index",
>     "resource.type": "index_expression",
>     "resource.id": "",
>     "index_uuid": "_na_",
>     "index": ""
>   },
>   "status": 404
> }

In console everything is ok:

> # curl -XGET 'http://localhost:9200/_cat/health'
> 1480896067 01:01:07 elasticsearch yellow 1 1 5 5 0 0 5 0 - 50.0%

In the elasticsearch log files, I have the following error message

> [2017-07-24T11:59:26,763][WARN ][o.e.d.r.RestController   ] Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header.

**Comment by consulthys** [comment]
The reason is explained in this blog post: https://www.elastic.co/blog/strict-content-type-checking-for-elasticsearch-rest-requests

Basically, starting with ES 5.3, ES will start requiring that the client send the `Content-Type` header along with all their requests. Until ES 6, it will be optional but as of ES 6, this will be mandatory and not modifiable.

So the data service should always add `Content-Type: application/json`to the requests sent to ES, or the REST tab should provide a way to either specify the content type or select from `application/json` or `application/x-yaml`

**Comment by soume86** [comment]
Hello,

I understood that it came from the Content-type, but the problem is that even if I specify in cerebro the Content-type (/_cat/health?format=json) this does not work.

It may be necessary to make modifications in cerebro?

Thank you for your answer.

**Comment by consulthys** [comment]
@soume86 it is not something that you are doing wrong, but something that needs to be changed inside the Cerebro codebase. Sorry if that wasn't clear.

**Comment by soume86** [comment]
Would you know if the change is planned or not?

Thank again,

**Comment by consulthys** [comment]
ping @lmenezes

**Comment by lmenezes** [comment]
hey. I will prepare a fix for this soon and create a new release.

**Comment by consulthys** [comment]
Any news on the next release @lmenezes ?

**Comment by consulthys** [comment]
This still doesn't seem to work on the latest 0.6.7 version.
