### ISSUE TITLE
status of cerebro

### ISSUE THREAD

**Issue by drummerwolli** [lmenezes/cerebro#340]
Hi, I was wondering about the status of the project. No commits since half a year, also no questions answered as well. I really like the project, have also some feature requests (e.g. snapshot overview is missing some information compared to https://github.com/lmenezes/elasticsearch-kopf) and could even do these changes myself, but first wanted to check in on the status here.

**Comment by lmenezes** [comment]
hey there and sorry for the long delay

although code and issues haven't been cared for in a longtime, this isn't because I no longer care about the project.

Personal matters pretty much took all of my free time, and completely disconnecting from this was what worked best for me.

I will starting having more time sometime next month, and will pick up both on pending issues as well as adding/improving features. Help is always nice though :)

**Comment by drummerwolli** [comment]
sure, no problem. please take care of personal matters first. this is what an OS project has to live with. glad to see that you will pick up things again. i will then have a look at some things and hopefully open up some PR's ...

**Comment by dforste** [comment]
Any update on the status here? There are 29 open PRs and several are security issues. Any idea if @lmenezes are going to start addressing them or opening up for others to review and merge commits?

**Comment by GYFgaoyuefei** [comment]
好的，我已收到
