### ISSUE TITLE
automatic refresh does not work v0.8.3

### ISSUE THREAD

**Issue by jeanpjm1** [lmenezes/cerebro#381]
Hello,

I installed Cerebro version v0.8.3 in elasticsearch version 7.2, but the option that chooses the automatic refresh time (5sec, 10sec, 15sec, 30sec, 1min) does not work refreshing the amount of index documents.

I have to refresh the index, to update the amount of existing documents

Does anyone know how to fix it?

Thanks
Jean

**Comment by lmenezes** [comment]
@jeanpjm1 I assume this doesn't really have anything to do with cerebro itself, but rather that your refresh interval might be pretty high, and hence it takes a long time to be seen?

As a question: if you create a new index, this does show up on the UI, right?

**Comment by jeanpjm1** [comment]
@lmenezes 

The time interval in the cerebro is 5 seconds, but it doesn't refresh, I can put any time interval that doesn't refresh automatically.

Yes, I can create an index normally in my user interface.

**Comment by lanerjo** [comment]
It sounds like you are expecting cerebro to auto refresh your indices using the elasticsearch api...
The refresh interval is how ofter cerebro refreshes the data you see.
Example:
5 second refresh - you create index, index appears in cerebro within 5 seconds
15 second refresh- you create index, index appears in cerebro within 5 seconds
N second refresh - you delete index, index still shows in cerebro for up to N seconds
N second refresh - the cpu usage on one of your nodes goes high, this will not show in cerebro until the next N second refresh interval

What I think you are expecting: 
you set a 5  second refresh interval, you expect the document count to update

What May be happening:
This could be caused due to your indices having a high refresh interval set in elasticsearch. In which case elasticsearch will only have the new documents available on an elasticsearch refresh of that index. 
Thus if your index is set to refresh every 60 seconds, new  documents will only be available every 60 seconds, even though your cerebro refresh may be set at 5 seconds...

**Comment by jeanpjm1** [comment]
Hello @lanerjo 

and how do i modify this time?

**Comment by rtkgjacobs** [comment]
@jeanpjm1 - some reading material for you ....

- https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html#index-refresh-interval-setting
- https://www.elastic.co/guide/en/elasticsearch/reference/current/tune-for-indexing-speed.html
- https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-refresh.html

If still unsure, you should check out or post on the elasticsearch forums
- https://discuss.elastic.co/

**Comment by lmenezes** [comment]
@jeanpjm1 As others kindly explained, this is not really a cerebro issue but just an ES topic :)
