### ISSUE TITLE
How to change log level?

### ISSUE THREAD

**Issue by debojitkakoti** [lmenezes/cerebro#468]
Not able to change the log level in cerebro docker.
I am trying to enable LDAP authentication but it fails without any error. It will be helpful if I can see debug logs to trace the error.

There is conf file for log in ` conf/logback.xml` but I don't see env variable in dockerfile and hence helm.

**Comment by moliware** [comment]
Hi!

Unfortunately the library we use for LDAP authentication doesn't output any logging even if you put the log level to debug. I added some examples of ldap configuration [here](https://github.com/lmenezes/cerebro/tree/master/examples). Hopefully that helps. Otherwise, please open a new issue with an example of configuration to see if we can help.
